# Generated by Django 5.2.7 on 2025-11-03 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_proyecto', models.IntegerField(unique=True)),
                ('plano', models.ImageField(blank=True, null=True, upload_to='planos')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('antecedentes', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('horas_disenio_teo', models.FloatField(null=True)),
                ('horas_fabricacion_teo', models.FloatField(null=True)),
                ('horas_montaje_teo', models.FloatField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='planificacion.cliente')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='planificacion.vendedor')),
            ],
        ),
    ]
