# Generated by Django 5.2.7 on 2025-10-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='horas_disenio_teo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='horas_fabricacion_teo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='horas_montaje_teo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='numero_proyecto',
            field=models.IntegerField(unique=True),
        ),
    ]
