# Generated by Django 5.2.7 on 2025-10-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0003_proyecto_horas_disenio_teo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='horas_disenio_teo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='horas_fabricacion_teo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='horas_montaje_teo',
            field=models.FloatField(null=True),
        ),
    ]
