# Generated by Django 5.2.7 on 2025-11-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0004_alter_proyecto_horas_disenio_teo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='antecedentes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='plano',
            field=models.ImageField(blank=True, null=True, upload_to='planos'),
        ),
    ]
