# Generated by Django 5.2.7 on 2025-11-03 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_disenio_real', models.FloatField()),
                ('horas_fabricacion_real', models.FloatField()),
                ('horas_montaje_real', models.FloatField()),
                ('incidencias', models.CharField(blank=True, max_length=200, null=True)),
                ('horas_disenio_teo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producciones_disenio_teo', to='planificacion.proyecto')),
                ('horas_fabricacion_teo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producciones_fabricacion_teo', to='planificacion.proyecto')),
                ('horas_montaje_teo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producciones_montaje_teo', to='planificacion.proyecto')),
                ('numero_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones_proyecto', to='planificacion.proyecto')),
            ],
        ),
    ]
