# Generated by Django 5.2.7 on 2025-10-31 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0004_alter_proyecto_horas_disenio_teo_and_more'),
        ('produccion', '0002_remove_produccion_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='horas_disenio_teo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producciones_disenio_teo', to='planificacion.proyecto'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='horas_fabricacion_teo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producciones_fabricacion_teo', to='planificacion.proyecto'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='horas_montaje_teo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producciones_montaje_teo', to='planificacion.proyecto'),
        ),
    ]
