# Generated by Django 5.2.7 on 2025-10-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_alter_produccion_horas_disenio_teo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='incidencias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
